//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public tblContact()
        {
            this.tblProjects = new HashSet<tblProject>();
            this.tblProjects1 = new HashSet<tblProject>();
        }
    
        public int ContactID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string C5_2 { get; set; }
        public string Badge { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public int CompanyID { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual ICollection<tblProject> tblProjects { get; set; }
        public virtual ICollection<tblProject> tblProjects1 { get; set; }
    }
}
