//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public tblCompany()
        {
            this.tblContacts = new HashSet<tblContact>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<tblContact> tblContacts { get; set; }
    }
}
