//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEndUser
    {
        public tblEndUser()
        {
            this.tblProjects = new HashSet<tblProject>();
        }
    
        public int EndUserID { get; set; }
        public string EndUserName { get; set; }
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
    }
}
