//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriority
    {
        public tblPriority()
        {
            this.tblProjects = new HashSet<tblProject>();
            this.tblTasks = new HashSet<tblTask>();
        }
    
        public int PriorityID { get; set; }
        public string PriorityName { get; set; }
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
        public virtual ICollection<tblTask> tblTasks { get; set; }
    }
}
