//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public tblProject()
        {
            this.tblTasks = new HashSet<tblTask>();
        }
    
        public int ProjectID { get; set; }
        public int EndUserID { get; set; }
        public int AssignedTo { get; set; }
        public int OpenedBy { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public int StatusID { get; set; }
        public string ProjectName { get; set; }
        public string SubCategory { get; set; }
        public int PriorityID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ScheduledStart { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> ScheduledFinish { get; set; }
        public string EstFinish { get; set; }
        public Nullable<System.DateTime> ActualFinish { get; set; }
        public Nullable<int> EstDurationDays { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string RelatedIssues { get; set; }
        public string Comments { get; set; }
        public int PublicityID { get; set; }
        public Nullable<double> PctComplete { get; set; }
        public string MgrComments { get; set; }
        public int GroupID { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblContact tblContact1 { get; set; }
        public virtual tblEndUser tblEndUser { get; set; }
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblPriority tblPriority { get; set; }
        public virtual tblPublicity tblPublicity { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual ICollection<tblTask> tblTasks { get; set; }
    }
}
