//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategory
    {
        public tblSubCategory()
        {
            this.tblTasks = new HashSet<tblTask>();
        }
    
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public int PhaseID { get; set; }
    
        public virtual tblPhase tblPhase { get; set; }
        public virtual ICollection<tblTask> tblTasks { get; set; }
    }
}
