//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabseFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int TaskID { get; set; }
        public int ProjectID { get; set; }
        public string Title { get; set; }
        public string EndUser { get; set; }
        public string AssignedTo { get; set; }
        public string OpenedBy { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public int StatusID { get; set; }
        public int SubCategoryID { get; set; }
        public int PriorityID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ScheduledStart { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> ScheduledFinish { get; set; }
        public string EstFinish { get; set; }
        public Nullable<System.DateTime> ActualFinish { get; set; }
        public Nullable<int> EstDurationDays { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string RelatedIssues { get; set; }
        public string Comments { get; set; }
        public string Publicity { get; set; }
        public Nullable<double> PctComplete { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> IISR { get; set; }
        public Nullable<bool> Atch { get; set; }
    
        public virtual tblPriority tblPriority { get; set; }
        public virtual tblProject tblProject { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
